'use strict';
// Stable context keys keep uploads and feedback attached to the displayed work.
function workKey(group,id,kind,holder){return [group,id,kind,holder].join(':');}
function workContext(key){
  const [group,id,kind,holderId]=key.split(':'),item=data[group]?.find(x=>x.id===id);
  const holder=kind==='version'?item?.versions.find(x=>x.id===holderId):item?.tasks.find(x=>x.id===holderId);
  return {key,group,id,kind,holderId,item,holder,active:!!item&&!item.archived&&!!holder&&!holder.deletedAt};
}
function workOp(ctx,kind,extra={}){return {kind,group:ctx.group,id:ctx.id,...(ctx.kind==='version'?{version:ctx.holderId}:{task:ctx.holderId}),...extra};}
function workField(ctx,field,value){return workOp(ctx,ctx.kind==='version'?'versionField':'taskField',{field,value});}
function smallX(attributes,label){return `<button type="button" class="small-x" ${attributes} aria-label="${esc(label)}" title="${esc(label)} · recoverable">×</button>`;}
function workGallery(holder,key){
  const images=C.activeImages(holder),columns=images.length===4?2:Math.min(4,images.length<7?3:4);
  const ctx=workContext(key);
  return `<div class="work-gallery task-image-gallery" style="--gallery-columns:${Math.max(1,Math.min(columns,images.length))}" data-count="${images.length}">${images.map(image=>`<figure class="work-image"><div class="work-image-frame"><button class="image-open" data-work-open="${esc(key)}" data-image-id="${image.id}" aria-label="Open ${esc(image.caption||'image')} and draw feedback"><img src="${esc(M.src(image.path))}" alt="${esc(image.caption||ROLES[image.role]||'Progress image')}" loading="lazy"></button><div class="image-tools"><button class="image-edit" data-work-replace="${esc(key)}" data-image-id="${image.id}" aria-label="Replace ${esc(image.caption||'image')}" title="Replace image · or drop an image here">${pencil}</button>${smallX(`data-work-delete-image="${esc(key)}" data-image-id="${image.id}"`,'Remove image')}</div></div><figcaption>${ctx.kind==='version'?`<select class="image-role" data-work-role="${esc(key)}" data-image-id="${image.id}" aria-label="Image type">${Object.entries(ROLES).map(([value,label])=>option(value,label,image.role)).join('')}</select>`:`<span class="eyebrow">${esc(ROLES[image.role]||'Progress')}</span>`}<textarea data-work-caption="${esc(key)}" data-image-id="${image.id}" aria-label="Image caption" maxlength="300" rows="1">${esc(image.caption)}</textarea>${ctx.kind==='version'?`<button class="text-button" data-work-cover="${esc(key)}" data-image-id="${image.id}">${ctx.item.cover===image.path?'✓ Main asset image':'Use as main asset image'}</button>`:''}</figcaption></figure>`).join('')||'<div class="empty">Add images to show your current work.</div>'}</div>${holder.images.some(i=>i.deletedAt)?`<details class="trash-list"><summary>Removed images (${holder.images.filter(i=>i.deletedAt).length})</summary>${holder.images.filter(i=>i.deletedAt).map(i=>`<div class="trash-row"><span>${esc(i.caption||'Image')}</span><button class="text-button" data-work-restore-image="${esc(key)}" data-image-id="${i.id}">Restore</button></div>`).join('')}</details>`:''}`;
}
function requestFields(holder,key){
  const ctx=workContext(key),summary=ctx.kind==='version'?'summary':'workSummary';
  return `<section class="review-request"><div class="sheet-heading"><h3>Creator’s update & review request</h3>${holder.requestedAt?smallX(`data-work-clear-request="${esc(key)}"`,'Remove feedback request'):''}</div><label><span class="field-heading">What changed? ${holder[summary]?smallX(`data-work-clear-update="${esc(key)}"`,'Remove creator update'):''}</span><textarea data-work-field="${summary}" data-work-context="${esc(key)}" maxlength="4000" placeholder="Describe your progress and decisions.">${esc(holder[summary]||'')}</textarea></label><label>What needs feedback?<textarea data-work-field="feedbackRequest" data-work-context="${esc(key)}" maxlength="4000" placeholder="Ask the team specific questions.">${esc(holder.feedbackRequest||'')}</textarea></label><div class="field-grid"><label>Ask for feedback from<select data-work-field="reviewTarget" data-work-context="${esc(key)}">${option('','Everyone',holder.reviewTarget||'')}${data.team.map(n=>option(n,n,holder.reviewTarget)).join('')}</select></label><div class="request-action"><button class="button primary" data-work-request="${esc(key)}">Request feedback →</button>${holder.requestedAt?`<small>${esc(holder.requestedBy||holder.owner)} · ${new Date(holder.requestedAt).toLocaleString()}</small>`:''}</div></div></section>`;
}
function workComments(holder,key){
  return `<div class="comments">${C.activeComments(holder).map(c=>`<article class="comment ${c.resolved?'resolved':''}"><div class="comment-meta"><strong>${esc(c.author)}</strong><span>${c.target?'→ '+esc(c.target):''}</span><time>${new Date(c.createdAt).toLocaleString()}</time>${smallX(`data-work-delete-comment="${esc(key)}" data-comment-id="${c.id}"`,'Remove feedback comment')}</div>${c.annotation?`<button class="annotation-feedback" data-feedback-image="${esc(c.annotation.path)}" data-feedback-title="${esc(c.body.slice(0,100))}"><img src="${esc(M.src(c.annotation.path))}" alt="Annotated feedback by ${esc(c.author)}" loading="lazy"><span>Open annotated feedback ↗</span></button>`:c.image?`<button class="text-button" data-work-open="${esc(key)}" data-image-id="${c.image}">${esc(holder.images.find(i=>i.id===c.image)?.caption||'View referenced image')}${c.point?` · marked at ${Math.round(c.point.x*100)}%, ${Math.round(c.point.y*100)}%`:''}</button>`:''}<p class="comment-body">${esc(c.body)}</p><label class="comment-resolve"><input type="checkbox" data-work-resolve="${esc(key)}" data-comment-id="${c.id}" ${c.resolved?'checked':''}>${c.resolved?'Resolved':'Mark resolved'}</label></article>`).join('')||'<p class="feedback-empty">No feedback yet. Open an image to draw on it, or post a comment below.</p>'}</div>${holder.comments.some(c=>c.deletedAt)?`<details class="trash-list"><summary>Removed feedback (${holder.comments.filter(c=>c.deletedAt).length})</summary>${holder.comments.filter(c=>c.deletedAt).map(c=>`<div class="trash-row"><span>${esc(c.author)} · ${esc(c.body.slice(0,90))}</span><button class="text-button" data-work-restore-comment="${esc(key)}" data-comment-id="${c.id}">Restore</button></div>`).join('')}</details>`:''}`;
}
function workCommentForm(key){
  const draft=reviewDrafts.get(key)||{};
  return `<form class="work-comment-form" data-work-comment="${esc(key)}"><div class="field-grid"><label>Posting as<select name="author" required>${option('','Choose your name',draft.author||identity)}${data.team.map(n=>option(n,n,draft.author||identity)).join('')}</select></label><label>Feedback for<select name="target">${option('','Everyone',draft.target||'')}${data.team.map(n=>option(n,n,draft.target||'')).join('')}</select></label></div><label>Your feedback<textarea name="body" required maxlength="6000" placeholder="What works? What should change?">${esc(draft.body||'')}</textarea></label><div class="dialog-actions"><button class="button primary" type="submit">Post feedback →</button></div></form>`;
}
function workUploadForm(key){const version=key.split(':')[2]==='version';return `<form class="upload-panel" data-work-upload="${esc(key)}"><h3>Add progress images</h3><div class="field-grid">${version?`<label>Image type<select name="role">${Object.entries(ROLES).map(([id,label])=>option(id,label,'progress')).join('')}</select></label>`:'<input type="hidden" name="role" value="progress">'}<label>Caption<input name="caption" maxlength="300" placeholder="What changed?"></label></div><label>Choose files or drop images here<input name="images" type="file" accept="image/png,image/jpeg,image/webp" multiple required></label><p class="help">PNG, JPEG or WebP · up to 15 MB each. Click an uploaded image to draw feedback.</p><button class="button primary" type="submit">${uploading?'Saving images…':'Add images ↑'}</button></form>`;}
function renderVersionWorkbench(){
  const {asset,version}=currentVersion();
  if(!asset){$('view').innerHTML='<div class="empty">No active assets. Restore an asset in Activity & recovery or add one on the Assets page.</div>';return;}
  const versions=C.activeVersions(asset),previous=version&&versions[versions.indexOf(version)-1],key=version&&workKey('assets',asset.id,'version',version.id);
  const compareImage=v=>C.activeImages(v).find(i=>i.role==='sheet')||C.activeImages(v)[0];
  $('view').innerHTML=`<div class="section-heading"><div><h2>Versions & feedback</h2><p>Keep the history. Show the progress. Improve it together.</p></div><button class="button primary" id="newVersionButton">+ New version</button></div><div class="review-toolbar"><label>Asset<select id="versionAsset">${C.activeAssets(data).map(a=>option(a.id,a.name,asset.id)).join('')}</select></label><label>Posting as<select id="feedbackIdentity">${option('','Choose your name',identity)}${data.team.map(n=>option(n,n,identity)).join('')}</select></label></div><div class="version-layout"><aside class="version-sidebar"><span class="eyebrow">VERSION HISTORY</span>${versionHistory(asset,version)}${deletedVersions(asset)}</aside><section class="version-main" data-asset="${asset.id}" data-version="${version?.id||''}">${version?`<div class="panel"><div class="version-title-row"><div><span class="eyebrow">${esc(asset.name)}</span><h3>${esc(version.title)}</h3></div>${previous?`<button class="button subtle" id="compareButton">${comparison?'Hide comparison':'Compare previous'}</button>`:''}</div><div class="version-fields"><label>Version name<input data-vfield="title" value="${esc(version.title)}" maxlength="150" required></label><label>Owner<select data-vfield="owner">${teamOptions(version.owner)}</select></label><label>Review status<select data-vfield="status">${Object.entries(VERSION_LABELS).map(([v,l])=>option(v,l,version.status)).join('')}</select></label></div>${requestFields(version,key)}${comparison&&previous?`<div class="compare-grid">${[previous,version].map(v=>`<div><span class="eyebrow">${esc(v.title)}</span>${compareImage(v)?`<img src="${esc(M.src(compareImage(v).path))}" alt="${esc(v.title)}">`:'<p>No image</p>'}</div>`).join('')}</div>`:''}<div class="sheet-heading"><h3>Images & current references</h3><span class="muted">${C.activeImages(version).length} images · click to inspect or draw</span></div>${workGallery(version,key)}${workUploadForm(key)}</div><section class="panel feedback-panel"><h3>Feedback & comments</h3>${workComments(version,key)}${workCommentForm(key)}</section>`:'<div class="panel empty"><h3>Create your next iteration</h3><button class="button primary" id="firstVersionButton">+ Create first version</button></div>'}</section></div>`;
}
function workReviewQueue(){return [...C.taskEntries(data,scopeFilter).filter(e=>e.task.status==='review').map(e=>workContext(workKey(e.group,e.item.id,'task',e.task.id))),...C.activeAssets(data).flatMap(a=>C.activeVersions(a).filter(v=>v.status==='review').map(v=>workContext(workKey('assets',a.id,'version',v.id))))];}
function renderReviewWorkbench(){
  const queue=workReviewQueue(),route=reviewKey.split('/'),selectedKey=route[0]==='versions'?workKey('assets',route[1],'version',route[2]):workKey(route[0],route[1],'task',route[2]);
  const ctx=queue.find(c=>c.key===selectedKey)||queue[0];
  if(ctx)reviewKey=ctx.kind==='version'?`versions/${ctx.id}/${ctx.holderId}`:`${ctx.group}/${ctx.id}/${ctx.holderId}`;
  $('view').innerHTML=`<div class="section-heading"><div><h2>Review</h2><p>Review versions and tasks together. Open an image to draw and post feedback.</p></div><span class="badge review">${queue.length} to review</span></div>${ctx?`<div class="review-workspace"><aside class="review-queue">${queue.map(c=>`<a class="review-queue-item ${c.key===ctx.key?'selected':''}" href="#review/${c.kind==='version'?'versions':c.group}/${c.id}/${c.holderId}"><strong>${esc(c.holder.title||c.holder.label)}</strong><small>${esc(c.item.name)} · ${c.kind}</small><span>${C.activeComments(c.holder).filter(c=>!c.resolved).length} open comments</span></a>`).join('')}</aside><section class="panel task-review"><div class="section-heading"><div><span class="eyebrow">${esc(ctx.item.name)}</span><h3>${esc(ctx.holder.title||ctx.holder.label)}</h3></div><a class="text-button" href="${ctx.kind==='version'?`#versions/${ctx.id}/${ctx.holderId}`:taskLink(ctx.group,ctx.item,ctx.holder)}">Edit ${ctx.kind} →</a></div><p class="review-description">${esc(ctx.holder.description||ctx.item.description)}</p><div class="review-decision"><button class="button" data-work-decision="${esc(ctx.key)}" data-status="${ctx.kind==='version'?'wip':'doing'}">Request changes</button><button class="button approve" data-work-decision="${esc(ctx.key)}" data-status="${ctx.kind==='version'?'approved':'done'}">Approve ✓</button></div>${requestFields(ctx.holder,ctx.key)}${workGallery(ctx.holder,ctx.key)}${workUploadForm(ctx.key)}<h3>Feedback & annotations</h3>${workComments(ctx.holder,ctx.key)}${workCommentForm(ctx.key)}</section></div>`:'<div class="empty"><h3>Nothing waiting for review</h3><p>Use Request feedback on a task or version to invite the team.</p><a class="button" href="#tasks">Open tasks →</a></div>'}`;
}
function hasWorkDrafts(){return [...document.querySelectorAll('[data-work-comment]')].some(f=>f.elements.body.value.trim())||[...document.querySelectorAll('[data-work-upload]')].some(f=>f.elements.images.files.length||f.elements.caption.value.trim())||[...document.querySelectorAll('[data-add-check],#addTaskForm')].some(f=>(f.elements.label||f.elements.task)?.value.trim());}
function captureWorkDrafts(){document.querySelectorAll('[data-work-comment]').forEach(f=>reviewDrafts.set(f.dataset.workComment,{body:f.elements.body.value,author:f.elements.author.value,target:f.elements.target.value}));}
async function uploadWorkImages(form){
  if(uploading||!canEditProject())return;
  const ctx=workContext(form.dataset.workUpload),files=[...form.elements.images.files],role=form.elements.role.value,caption=form.elements.caption.value.trim();
  if(!ctx.active||!files.length)return;
  if(ctx.holder.images.length+files.length>64){setMessage('Up to 64 images per task or version, including recoverable images.',true);return;}
  uploading=true;applyEditorAccess();
  try{for(const file of files){const blob=await M.prepare(file),id=newId('image'),path=`uploads/${id}.webp`;await M.store(path,blob);if(!workContext(ctx.key).active)throw new Error('This work was removed. Restore it before adding images.');commit(workOp(ctx,ctx.kind==='version'?'addImage':'addTaskImage',{value:{id,path,role:ctx.kind==='version'?role:'progress',caption:caption||file.name}}));}form.reset();}
  catch(error){setMessage(error.message,true);}finally{uploading=false;renderSharedUpdate();}
}
function refreshWorkDetail(){if(detail&&$('detailDialog').open){const old={...detail},scroll=$('detailDialog').scrollTop,opened=[...$('detailDialog').querySelectorAll('details[open]')].map(d=>d.closest('[data-task-row]')?.dataset.taskRow).filter(Boolean);saveUnfinishedFields($('detailDialog'));openDetail(old.group,old.id);opened.forEach(id=>$('task-'+id)?.querySelector('details')?.setAttribute('open',''));$('detailDialog').scrollTop=scroll;}}
function postWorkComment(key,body,author,target='',image='',annotation){
  const ctx=workContext(key);if(!ctx.active)throw new Error('Restore this task or version before posting feedback.');
  if(ctx.holder.comments.length>=500)throw new Error('This work has reached its 500-comment limit, including recoverable comments.');
  const value={id:newId('comment'),author,target,image,body,createdAt:new Date().toISOString(),resolved:false,...(ctx.kind==='task'?{point:null}:{}),...(annotation?{annotation}:{})};
  return commit({...workOp(ctx,ctx.kind==='version'?'addComment':'addTaskComment',{value}),context:key});
}
function openWorkReplacement(key,imageId){
  const ctx=workContext(key),image=ctx.holder?.images.find(i=>i.id===imageId);if(!ctx.active||!image||image.deletedAt)return;
  if(ctx.kind==='version'){openImageEditor(`version:${ctx.id}:${ctx.holderId}:${imageId}`);return;}
  imageEdit={kind:'task',context:key,imageId};const f=$('thumbnailForm');f.reset();resetUploadHints(f);$('thumbnailError').textContent='';$('thumbnailCurrent').src=M.src(image.path);$('thumbnailTitle').textContent='Replace progress image';$('thumbnailCaptionLabel').hidden=false;f.elements.caption.value=image.caption;$('thumbnailHelp').textContent='The original stays recoverable in Activity & recovery. Linked comments stay attached.';$('thumbnailDialog').showModal();applyEditorAccess();
}
document.addEventListener('input',e=>{if(e.target.matches?.('[data-work-field],[data-work-caption]'))unfinishedFields.add(e.target);if(e.target.closest('[data-work-comment]'))captureWorkDrafts();});
document.addEventListener('change',e=>{
  const el=e.target;
  if(el.dataset.workField){const ctx=workContext(el.dataset.workContext);if(ctx.active)commit(workField(ctx,el.dataset.workField,el.value.trim()));}
  if(el.dataset.workCaption){const ctx=workContext(el.dataset.workCaption);if(ctx.active)commit(workOp(ctx,ctx.kind==='version'?'versionImageField':'taskImageField',{image:el.dataset.imageId,field:'caption',value:el.value.trim()}));}
  if(el.dataset.workRole){const ctx=workContext(el.dataset.workRole);if(ctx.active&&ctx.kind==='version')commit(workOp(ctx,'versionImageField',{image:el.dataset.imageId,field:'role',value:el.value}));}
  if(el.dataset.workResolve){const ctx=workContext(el.dataset.workResolve);if(ctx.active)commit(workOp(ctx,ctx.kind==='version'?'commentResolved':'taskCommentResolved',{comment:el.dataset.commentId,value:el.checked}));}
});
document.addEventListener('click',e=>{
  const open=e.target.closest('[data-work-open]');if(open){openAnnotationViewer(open.dataset.workOpen,open.dataset.imageId);return;}
  const feedback=e.target.closest('[data-feedback-image]');if(feedback){$('largeImage').src=M.src(feedback.dataset.feedbackImage);$('imageTitle').textContent=feedback.dataset.feedbackTitle;$('largeImage').alt='Annotated feedback';$('imageDialog').showModal();return;}
  const replace=e.target.closest('[data-work-replace]');if(replace){openWorkReplacement(replace.dataset.workReplace,replace.dataset.imageId);return;}
  for(const [attr,entity,deleted] of [['workDeleteImage','Image',true],['workRestoreImage','Image',false],['workDeleteComment','Comment',true],['workRestoreComment','Comment',false]]){
    const button=e.target.closest(`[data-${attr.replace(/[A-Z]/g,m=>'-'+m.toLowerCase())}]`);if(!button)continue;
    const ctx=workContext(button.dataset[attr]);if(!ctx.active)return;
    commit(workOp(ctx,(ctx.kind==='version'?'version':'task')+entity+'Deleted',{[entity==='Image'?'image':'comment']:button.dataset[entity==='Image'?'imageId':'commentId'],value:deleted?new Date().toISOString():''}));refreshWorkDetail();return;
  }
  const cover=e.target.closest('[data-work-cover]');if(cover){const ctx=workContext(cover.dataset.workCover),image=ctx.holder?.images.find(i=>i.id===cover.dataset.imageId);if(ctx.active&&image)commit({kind:'field',group:'assets',id:ctx.id,field:'cover',value:image.path});return;}
  const clearUpdate=e.target.closest('[data-work-clear-update]');if(clearUpdate){const ctx=workContext(clearUpdate.dataset.workClearUpdate);commit(workField(ctx,ctx.kind==='version'?'summary':'workSummary',''));renderSharedUpdate();return;}
  const request=e.target.closest('[data-work-request],[data-work-clear-request]');
  if(request){const key=request.dataset.workRequest||request.dataset.workClearRequest;saveUnfinishedFields(request.closest('section')||$('view'));const ctx=workContext(key);if(!ctx.active)return;if(!identity){setMessage('Choose your name before requesting feedback.',true);return;}const clear=!!request.dataset.workClearRequest;
    const ops=[workField(ctx,'requestedAt',clear?'':new Date().toISOString()),workField(ctx,'requestedBy',clear?'':identity)];if(clear)ops.push(workField(ctx,'feedbackRequest',''),workField(ctx,'reviewTarget',''));
    ops.push(ctx.kind==='version'?workField(ctx,'status',clear?'wip':'review'):workOp(ctx,'task',{value:clear?'doing':'review'}));commit({kind:'batch',ops,label:clear?'Removed feedback request':'Requested feedback',context:key});refreshWorkDetail();return;}
  const decision=e.target.closest('[data-work-decision]');if(decision){const ctx=workContext(decision.dataset.workDecision);if(ctx.active)commit(ctx.kind==='version'?workField(ctx,'status',decision.dataset.status):workOp(ctx,'task',{value:decision.dataset.status}));}
});
document.addEventListener('submit',e=>{
  const f=e.target;if(f.dataset.workUpload){e.preventDefault();uploadWorkImages(f);}
  if(f.dataset.workComment){e.preventDefault();if(!canEditProject())return;const body=f.elements.body.value.trim(),author=f.elements.author.value;if(!body||!author)return;try{const key=f.dataset.workComment,target=f.elements.target.value;f.elements.body.value='';reviewDrafts.delete(key);if(postWorkComment(key,body,author,target)){render(true);}else{reviewDrafts.set(key,{body,author});render(true);}}catch(error){setMessage(error.message,true);}}
});
