const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const C = require('../core.js');
const data = require('./fixture.cjs')();
assert.equal(C.validate(data).assets.length,6);
assert.equal(data.shots.length,5);
assert(data.shots.every(s=>s.tasks.length===7));
const local=[{kind:'task',group:'assets',id:'knight',task:'design',value:'done'},{kind:'field',group:'assets',id:'knight',field:'notes',value:'Æøå · local note'}];
const remote=C.clone(data);remote.assets[1].owner='Kevin';remote.assets[0].tasks[1].status='doing';
const merged=C.replay(remote,local);
assert.equal(merged.assets[1].owner,'Kevin');
assert.equal(merged.assets[0].tasks[1].status,'doing');
assert.equal(merged.assets[0].tasks[0].status,'done');
assert.equal(merged.assets[0].notes,'Æøå · local note');
assert.equal(C.progress(merged.assets[0]),17);
assert.equal(C.status(merged.assets[0]),'active');
merged.assets[0].tasks.forEach(t=>t.status='done');assert.equal(C.status(merged.assets[0]),'done');
merged.assets[0].blocked=true;assert.equal(C.status(merged.assets[0]),'blocked');
const backup=C.validate(JSON.parse(JSON.stringify(merged)));assert.equal(backup.assets[0].notes,'Æøå · local note');
assert.equal(C.safeUrl('javascript:alert(1)'),'');assert.equal(C.safeUrl('data:text/html,evil'),'');assert.equal(C.safeUrl('https://example.com/file.blend'),'https://example.com/file.blend');
for(const mutate of [d=>d.assets[0].id='../evil',d=>d.assets[0].tasks[0].status='invalid',d=>d.assets[0].file='javascript:alert(1)',d=>d.shots[0].dependencies=['missing'],d=>d.assets.push(d.assets[0]),d=>d.team=[]]){const bad=C.clone(data);mutate(bad);assert.throws(()=>C.validate(bad));}
const added={kind:'addTask',group:'assets',id:'knight',value:{id:'custom_task',label:'Check silhouette',description:'',status:'todo'}};
assert.equal(C.replay(data,[added,added]).assets[0].tasks.length,7);
const gate=C.replay(data,[{kind:'milestone',id:'story',check:'scope',value:true}]);assert.equal(gate.milestones[0].checks[0].done,true);assert.equal(data.milestones[0].checks[0].done,false);
const version={id:'test_v2',title:'v002',summary:'Cloth revision',owner:'Jens',status:'review',createdAt:'2026-10-05T19:00:00.000Z',images:[],comments:[]};
const image={id:'test_image',path:'uploads/test_image.webp',role:'clothing-progress',caption:'New cloth'};
const comment={id:'kevin_comment',author:'Kevin',target:'Jens',image:'test_image',body:'Try a heavier hem.',createdAt:'2026-10-05T19:01:00.000Z',resolved:false};
const versionOps=[{kind:'addVersion',group:'assets',id:'troll',value:version},{kind:'addImage',group:'assets',id:'troll',version:'test_v2',value:image},{kind:'addComment',group:'assets',id:'troll',version:'test_v2',value:comment}];
const iterated=C.replay(data,versionOps);assert.equal(iterated.assets[1].versions.at(-1).images[0].role,'clothing-progress');assert.equal(iterated.assets[1].versions.at(-1).comments[0].author,'Kevin');C.validate(iterated);
const jensComment={...comment,id:'jens_comment',author:'Jens',body:'Will update in v003.'};
const together=C.replay(iterated,[{kind:'addComment',group:'assets',id:'troll',version:'test_v2',value:jensComment},{kind:'addComment',group:'assets',id:'troll',version:'test_v2',value:comment}]);assert.equal(together.assets[1].versions.at(-1).comments.length,2);
const resolved=C.replay(together,[{kind:'commentResolved',group:'assets',id:'troll',version:'test_v2',comment:'kevin_comment',value:true}]);assert(resolved.assets[1].versions.at(-1).comments[0].resolved);
const withCover=C.clone(together);withCover.assets[1].cover=image.path;
const replacement={kind:'replaceImage',group:'assets',id:'troll',version:'test_v2',image:'test_image',value:{path:'uploads/replacement.webp',caption:'Improved cloth'}};
const replaced=C.replay(withCover,[replacement]);
assert.equal(replaced.assets[1].cover,'uploads/replacement.webp');
assert.equal(replaced.assets[1].versions.at(-1).images[0].caption,'Improved cloth');
assert.equal(replaced.assets[1].versions.at(-1).images[0].role,'clothing-progress');
assert.equal(replaced.assets[1].versions.at(-1).comments[0].image,'test_image');
assert.deepEqual(replaced.assets[1].versions[0],data.assets[1].versions[0]);
assert.equal(withCover.assets[1].versions.at(-1).images[0].path,image.path);
const teammateCover=C.clone(withCover);teammateCover.assets[1].cover='uploads/teammate.webp';
assert.equal(C.replay(teammateCover,[replacement]).assets[1].cover,'uploads/teammate.webp');
const banner=C.replay(replaced,[{kind:'project',field:'hero',value:'uploads/banner.webp'}]);C.validate(banner);
const invalidBanner=C.clone(banner);invalidBanner.hero='../../secret';assert.throws(()=>C.validate(invalidBanner));
const malicious=C.clone(iterated);malicious.assets[1].versions.at(-1).images[0].path='../../secret';assert.throws(()=>C.validate(malicious));
const withMedia={...data,localImages:[{path:'uploads/test_image.webp',base64:'test'}]};assert.equal(C.validate(withMedia).localImages,undefined);
const context={window:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../seed.js'),'utf8'),context);assert.deepEqual(C.validate(context.window.ETERNAL_TOMB_SEED).assets.map(a=>a.id),data.assets.map(a=>a.id));
console.log('Passed: project schema, progress, task editing, Unicode backup, safe image paths, milestone state, seed consistency, version history, image metadata, comment resolution and teammate merge preservation.');
